# Dockerfile
FROM chromium-base as base

# Nastavení pracovního adresáře
WORKDIR /software

# Nejprve zkopíruj jen requirements.txt
COPY requirements.txt /software/requirements.txt

# Nainstaluj balíčky (včetně PyTorch)
RUN pip install --no-cache-dir -r /software/requirements.txt

# A teprve pak zkopíruj zbytek
COPY . /software

# Nastavení Python path, aby šlo importovat "database"
ENV PYTHONPATH="/software"

# Exponování portu 5000 (pro flask)
EXPOSE 5000

# Nastavení pracovní složky Flasku
WORKDIR /software/web_api


